forEach: BoundedContext
path: {{nameCamelCase}}/{{nameCamelCase}}-boot/src/main/resources
fileName: application.yml
---
server:
  servlet:
    context-path: /{{name}}-sample
spring:
  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: ${datasource.driver-class-name}
    hikari:
      maximum-pool-size: ${datasource.hikari.maximum-pool-size}
      minimum-idle: ${datasource.hikari.minimum-idle}
  mvc:
    converters:
      preferred-json-mapper: gson
