forEach: BoundedContext
path: {{nameCamelCase}}/{{nameCamelCase}}-boot/src/main/resources
fileName: application-local.yml
---
server:
  port: 8088
datasource:
  url: jdbc:postgresql://10.125.2.121:5432/jiradb
  username: jirauser
  password: jira12#
  driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 3
    minimum-idle: 1
logging:
  config: classpath:log4j2-local.xml
